name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
    - run: rustup target add x86_64-pc-windows-gnu
    - run: sudo apt update && sudo apt install -y gcc-mingw-w64-x86-64
    - uses: actions/checkout@v4
    - name: Build Linux
      run: cargo build --release
    - name: Bulid Windows
      run: cargo build --release --target x86_64-pc-windows-gnu
    - name: Upload Linux Binary
      uses: actions/upload-artifact@v4
      with:
        name: linux-binary
        path: target/release/vacuum-cs
    - name: Upload Windows Binary
      uses: actions/upload-artifact@v4
      with:
        name: windows-binary
        path: target/x86_64-pc-windows-gnu/release/vacuum-cs.exe